[tool.poetry]
name = "mmq"
version = "0.1.0"
description = "The Majorize-Minimize-Quadratic toolbox"
authors = ["François Orieux <orieux@l2s.centralesupelec.fr>"]
license = "GPL"

[tool.poetry.dependencies]
python = "^3.8"
numpy = "^1.19.4"

[tool.poetry.dev-dependencies]
ipython = "^7.19.0"
jedi = "0.17.2"
oct2py = "^5.2.0"
matplotlib = "^3.3.3"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
